repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: pretty-format-json
        args: [ --autofix ]
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.9
    hooks:
      - id: shellcheck
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.1
    hooks:
      - id: markdownlint
